### ISSUE TITLE
Cannot enable plugin in OJS3 Testdrive

### ISSUE THREAD

**Issue by fgnievinski** [pkp/translator#54]
Hi.  Unfortunately the Translator plugin cannot be enabled -- it's not listed in the section for Generic plugins, although it's listed in the tab for Plugin library (so I assume it's installed properly).

I've tried both our local installation and the OJS3 testdrive (made available by PKP, using the administrator login):

https://demo.publicknowledgeproject.org/ojs3/testdrive/index.php/testdrive-journal/management/settings/website

Maybe the problem is related to the following caveat mentioned in the README?

> Note that this plugin must be able to read and write translation-related files on the server.

**Comment by asmecher** [comment]
@fgnievinski, this is a Site-wide plugin (as opposed to journal-specific), because it affects all journals in the installation. Accordingly it needs to be accessed from the Administrator's plugins area, not the journal-specific (journal manager's) plugins area.

Note that we're going to drop support for this plugin in the future, as we're moving to `.po`-based log files.

If you're looking for general Q&A and aren't sure whether you're reporting a bug, the forum (https://support.pkp.sfu.ca) is a better place.
